### ISSUE TITLE
setup-stdlib.bat installs probably unnecessary mod files

### ISSUE THREAD

**Issue by degawa** [LKedward/quickstart-fortran#1]
Thank you for releasing such great software. :tada:
I installed it immediately and tried it out. I like it very much because it is easy, helpful, and convenient.

After installing quickstart-fortran, I built and installed stdlib using the contained bat file, setup-stdlib.bat.

In the installed directory `%USERPROFILE%\AppData\Local\quickstart_fortran\mingw64\lib\gcc\x86_64-w64-mingw32\10.3.0\finclude`, I found many mod files with the prefix `test_`. I think these are mod files created during the build of tests of stdlib, located in `stdlib\test` directory, and are not required for using and linking the stdlib.

Can I configure those not to be installed?

**Comment by LKedward** [comment]
Thanks for the feedback @degawa! I've now updated the `setup-stdlib` helper script to remove these unnecessary mod files.

You can see the changes here: 297d0bccea777512473f541cea126658d393b866, and the new release is available [here](https://github.com/LKedward/quickstart-fortran/releases/tag/v1.1).

**Comment by degawa** [comment]
Thank you for your quick response.

I installed the new release version and launched `setup-stdlib`.
I confirmed that it perfectly resolved my concern.

Excellent work :thumbsup:
Thank you.
